# -*- coding: utf-8 -*-
"""Malaria.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0ygTSzpESfWU_yERvgKmH8j28Mt6iqF

# Projeto de Estudos: Malária
"""

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('sorted.csv', index_col=False)

"""## Análise dos países mais afetados"""

# New dataframe with 10 most affected countries in relation to all the others
dfo = df.head(10)
temp = df.drop(labels=list(range(10)))
temp = temp.drop(labels=[194])
dfo.loc[10] = temp.sum(numeric_only=True)
dfo.loc[10, 'Country'] = 'Other'

fig = px.pie(dfo, names='Country', values='Total', title='10 countries with the most deaths', height=500, width=1000)
fig.show()

fig = px.bar(df.head(10), x='Country', y='Total', title='10 countries with the most deaths', height=500, width=1000)
fig.show()

"""## Análise da mortalidade ao longo dos anos"""

df1 = df.set_index('Country')
df1 = df1.drop(['Total'], axis=1)
df1 = df1.T
df1 = df1.reset_index()
df1 = df1.rename(columns={'index':'Year'})

fig = px.line(df1, x='Year', y='All', title='Malaria Deaths Worldwide', height=500, width=1000)
m = df1["All"].max()
fig.add_annotation(x=int(df1.iloc[df1["All"].idxmax()]["Year"]) - 2000, y=m, text= 'Peak: ' + str(m), arrowside='start', bgcolor='yellow')
fig.show()

"""### Análise da média e mediana total de casos"""

# Visualizando a média e a mediana dos dados:
#Calculo da media e mediana
media = df['Total'].mean()
mediana = df['Total'].median()
media = round(media, 2)
mediana = round(mediana, 2)

#Criacao da figura e insercao das anotacoes com os dados calculados anteriormente
fig = px.box(df, y="Total", title="Distribution of the Total Number of Deaths", height=500, width=500, points="all")
fig.add_annotation(x=0, y=1000000, text="Mean: " + str(media), showarrow=True, bgcolor="orange")
fig.add_annotation(x=0, y=5, text="Median: " + str(mediana), showarrow=True, bgcolor="yellow")

#Apresentacao da figura
fig.show()

# Visualizando a média e a mediana dos dados:
#Filtragem de dados
filtro = df['Total'] > 0 
filtrado = df[filtro]

#Calculo das medias e medianas
media = filtrado['Total'].mean()
mediana = filtrado['Total'].median()
media = round(media, 2)
mediana = round(mediana, 2)

#Criacao da figura e insercao das anotacoes com os dados calculados anteriormente
fig = px.box(filtrado, y="Total", title="Distribution of the Total Number of Deaths", height=500, width=500, points="all")
fig.add_annotation(x=0, y=1000000, text="Mean: " + str(media), showarrow=True, bgcolor="orange")
fig.add_annotation(x=0, y=5, text="Median: " + str(mediana), showarrow=True, bgcolor="yellow")

#Apresentacao da figura
fig.show()

#FIltragem de dados
filtro = df['Total'] > 0 
filtrado = df[filtro]
filtro2 = filtrado['Total'] < 1000
filtrado = filtrado[filtro2]

#Calculo da media e da mediana
media = filtrado['Total'].mean()
mediana = filtrado['Total'].median()
media = round(media, 2)
mediana = round(mediana, 2)

#Criacao da figura e insercao de anotacoes com os dados calculados anteriormente
fig = px.box(filtrado, y="Total", title="Distribution of the Total Number of Deaths", width=500, height=500, points="all")
fig.add_annotation(x=0, y=media, text="Mean: " + str(media), showarrow=True, bgcolor="orange")
fig.add_annotation(x=0, y=mediana, text="Median: " + str(mediana), showarrow=True, bgcolor="yellow")

#Apresentacao da figura
fig.show()

#Filtragem de dados
filtro = df['2000'] > 0
filtrado = df[filtro]

filtro2 = filtrado['2001'] > 0
filtrado = filtrado[filtro2]

filtro3 = filtrado['2002'] > 0
filtrado = filtrado[filtro3]

#Criacao e apresentacao da figura
fig = px.box(filtrado, y=['2000', '2001', '2002'], points="all", title="Distribution of Deaths in the Deadliest Years", labels={"value": "Number of Deaths", "variable": "Deadliest Years"})
fig.show()

#Filtragem de dados
filtro = df['2000'] > 0
filtrado = df[filtro]
filtro2 = df['2000'] < 1000
filtrado = filtrado[filtro2]

filtro3 = filtrado['2001'] > 0
filtrado = filtrado[filtro3]
filtro4 = filtrado['2001'] < 1000
filtrado = filtrado [filtro4]

filtro5 = filtrado['2002'] > 0
filtrado = filtrado[filtro5]
filtro6 = filtrado['2002'] < 1000
filtrado = filtrado [filtro6]

#Criacao da figura
fig = px.box(filtrado, y=['2000', '2001', '2002'], points="all", title="Distribution of Deaths in the Deadliest Years", labels={"value": "Number of Deaths", "variable": "Deadliest Years"})

#Calculo das medias e medianas e insercao como anotacoes da figura
media2000 = filtrado['2000'].mean()
mediana2000 = filtrado['2000'].median()
media2000 = round(media2000, 2)
fig.add_annotation(x=0, y=media2000, text="Mean: " + str(media2000), showarrow=True, bgcolor="orange")
fig.add_annotation(x=0, y=mediana2000, text="Median: " + str(mediana2000), showarrow=True, bgcolor="yellow")

media2001 = filtrado['2001'].mean()
mediana2001 = filtrado['2001'].median()
media2001 = round(media2001, 2)
fig.add_annotation(x=1, y=media2001, text="Mean: " + str(media2001), showarrow=True, bgcolor="orange")
fig.add_annotation(x=1, y=mediana2001, text="Median: " + str(mediana2001), showarrow=True, bgcolor="yellow")

media2002 = filtrado['2002'].mean()
mediana2002 = filtrado['2002'].median()
media2002 = round(media2002, 2)
fig.add_annotation(x=2, y=media2002, text="Mean: " + str(media2002), showarrow=True, bgcolor="orange")
fig.add_annotation(x=2, y=mediana2002, text="Median: " + str(mediana2002), showarrow=True, bgcolor="yellow")

#Apresentacao da figura formada
fig.show()

"""### Análise de Bursts:"""

filtro1 = df['Total'] > 0
filtrado = df[filtro1]
filtro2 = filtrado['Country'] != 'All'
filtrado = filtrado[filtro2]

melted_df = filtrado.melt(var_name= 'Years', value_name= 'Cases', id_vars=['Country'], value_vars=['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014', '2015', '2016','2017'])
fig = px.line(melted_df, x='Years', y='Cases', color='Country', title = 'Worldwide Malaria Cases per Country (2000 - 2017)', height=500, width=1000)
fig.show()

fig = px.line(df1, x='Year', y='Brazil', title='Malaria Deaths Brazil', height=500, width=1000)
fig.show()

fig = px.line(df1, x='Year', y=df1.columns[0:3], title='Malaria Deaths Nigeria and Congo', height=500, width=1000, labels={"value": "Number of Deaths", "variable": "Countries"})
fig.show()

fig = px.line(df1, x='Year', y=df1.columns[3:10], title='Other Countries', height=500, width=1000, labels={"value": "Number of Deaths", "variable": "Countries"})
fig.show()

"""### Análise por Continentes:"""

df2 = pd.read_csv('Continentes.csv')

f1 = df2['Total']>0
filtrado2 = df2[f1]
f2 = filtrado2['Country'] != 'All'
filtrado2 = filtrado2[f2]

melted_df2 = filtrado2.melt(var_name= 'Years', value_name= 'Cases', id_vars=['Continent', 'Country'], value_vars=['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017'])

fig = px.area(melted_df2, x="Years", y="Cases", color="Continent", line_group="Country", title='Malaria Deaths per Continent')
fig.show()